### PR TITLE
Fixed an error when there is no item of key.

### PR DESCRIPTION
**Pull request by naxxster**
DynamoDB update_item makes an error when there is no item with the key to update.
Make the update_item to create new item by using if_not_exits function with base value of 0.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jinspark-lab** [comment]
As I understand, DynamoDB UpdateItem does Upsert. Could you please check?
(https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html)

**Comment by jinspark-lab** [comment]
I also check as soon as possible.

**Comment by naxxster** [comment]
When I used the previous code that access attributes without if_not_exist function, the update_item request failed with an error. I will paste the error after I test it again.

After I change the code. the update_item request operates successfully and the item was inserted also.

Feel free to test the case.

**Comment by naxxster** [comment]
I tested with the following cli commands:

```
❯ # Success
❯ aws dynamodb update-item --table-name TestTable --key '{"Name":{ "S": "1" }}' --update-expression 'SET Score = :score' --expression-attribute-values '{ ":score": { "N": "1" }}'
❯ # Failed
❯ aws dynamodb update-item --table-name TestTable --key '{"Name":{ "S": "2" }}' --update-expression 'SET Score = Score + :score' --expression-attribute-values '{ ":score": { "N": "1" }}'

An error occurred (ValidationException) when calling the UpdateItem operation: The provided expression refers to an attribute that does not exist in the item
❯ # Success
❯ aws dynamodb update-item --table-name TestTable --key '{"Name":{ "S": "2" }}' --update-expression 'SET Score = if_not_exists(Score, :basescore) + :score' --expression-attribute-values '{ ":score": { "N": "1" }, ":basescore": {"N": "100"}}' # Success
```

`UpdateItem` fails with an error when the `update-expression` references attribute of an item that does not exist.

**Comment by jinspark-lab** [comment]
Checked. Thanks!

**Pull request merged**
